[workspace]
members = [
    "tasks/core_algorithmic_foundations/parallel_csv_reader",
    "tasks/multi_language_cross_integration/ffi_bridge",
    "tasks/multi_language_cross_integration/wasm_dot"
]
resolver = "2"
