[package]
name = "ffi_bridge"
version = "0.1.0"
edition = "2021"
description = "Rust side of the Swift ↔ Rust roundtrip bridge"
license = "MIT"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[features]
default = []
swift = []

[dependencies]
log = "0.4"
