apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: overlay
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/example/backend-config
    targetRevision: main
    path: overlays/production
    directory:
      recurse: true
      jsonnet:
        tlas:
          environment: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
  info:
    - name: PagerDuty Escalation Policy
      value: https://pagerduty.example.com/escalation/backend
    - name: On-call Slack Channel
      value: https://slack.example.com/archives/backend-oncall
  revisionHistoryLimit: 5
