name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint ${{ matrix.language }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [node, python, rust]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install Node dependencies
        if: matrix.language == 'node'
        run: npm ci
      - name: Run ESLint
        if: matrix.language == 'node'
        run: npm run lint
      - name: Setup Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements-dev.txt
      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Python lint
        if: matrix.language == 'python'
        run: |
          pip install black==24.4.2 mypy==1.11.1
          black --check tasks tests
          mypy tasks
      - name: Setup Rust
        if: matrix.language == 'rust'
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Rust lint
        if: matrix.language == 'rust'
        run: |
          if [ -f Cargo.toml ]; then
            cargo clippy --workspace --all-targets -- -D warnings
          else
            echo "No Cargo.toml detected; skipping Rust lint."
          fi

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build --if-present
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install build
          python -m build
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          if [ -f Cargo.toml ]; then
            cargo build --workspace --release
          else
            echo "No Cargo.toml detected; skipping cargo build."
          fi

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pytest
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          if [ -f Cargo.toml ]; then
            cargo test --workspace
          else
            echo "No Cargo.toml detected; skipping cargo test."
          fi
